"""
This type stub file was generated by pyright.
"""

import string

PY3 = ...
if PY3:
    string = ...
class StringProcessor:
    """
    This class defines method to process strings in the most
    efficient way. Ideally all the methods below use unicode strings
    for both input and output.
    """
    regex = ...
    @classmethod
    def replace_non_letters_non_numbers_with_whitespace(cls, a_string): # -> str:
        """
        This function replaces any sequence of non letters and non
        numbers with a single white space.
        """
        ...
    
    strip = ...
    to_lower_case = ...
    to_upper_case = ...


